# Generated by Django 2.2 on 2019-05-04 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='created_date',
        ),
        migrations.AddField(
            model_name='logitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
