# Generated by Django 2.2 on 2019-05-16 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0002_auto_20190504_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bullshit_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
